export const SHOW_NEXT_IMG = "SHOW_NEXT_IMG";
export const FETCH_IMAGE = "FETCH_IMAGE";
export const FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_FAIL = "FETCH_IMAGE_FAIL";

export default {
  SHOW_NEXT_IMG,
  FETCH_IMAGE,
  FETCH_IMAGE_SUCCESS,
  FETCH_IMAGE_FAIL,
};
